// <auto-generated />
using System;
using BGG.Bot.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BGG.Bot.Data.Migrations
{
    [DbContext(typeof(CollectionContext))]
    [Migration("20210503044631_played-items")]
    partial class playeditems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BGG.Bot.Data.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BggId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BGG.Bot.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BggUsername")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BGG.Bot.Data.Models.UserCollectionItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BggId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForTrade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Owned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreOrdered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreviouslyOwned")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Rating")
                        .HasColumnType("REAL");

                    b.Property<bool>("Want")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WantToBuy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WantToPlay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WishList")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WishlistPriority")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "BggId");

                    b.HasIndex("BggId");

                    b.ToTable("UserCollectionItem");
                });

            modelBuilder.Entity("BGG.Bot.Data.Models.UserPlayedItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BggId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("UserId", "BggId");

                    b.HasIndex("BggId");

                    b.ToTable("UserPlayedItems");
                });

            modelBuilder.Entity("BGG.Bot.Data.Models.UserCollectionItem", b =>
                {
                    b.HasOne("BGG.Bot.Data.Models.Item", "Item")
                        .WithMany("UserCollectionItems")
                        .HasForeignKey("BggId")
                        .HasPrincipalKey("BggId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGG.Bot.Data.Models.User", "User")
                        .WithMany("UserCollectionItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BGG.Bot.Data.Models.UserPlayedItem", b =>
                {
                    b.HasOne("BGG.Bot.Data.Models.Item", "Item")
                        .WithMany("UserPlayedItems")
                        .HasForeignKey("BggId")
                        .HasPrincipalKey("BggId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGG.Bot.Data.Models.User", "User")
                        .WithMany("UserPlayedItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BGG.Bot.Data.Models.Item", b =>
                {
                    b.Navigation("UserCollectionItems");

                    b.Navigation("UserPlayedItems");
                });

            modelBuilder.Entity("BGG.Bot.Data.Models.User", b =>
                {
                    b.Navigation("UserCollectionItems");

                    b.Navigation("UserPlayedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
